//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 11:33:19 AM BDT 
//


package com.optima.Way4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="errorcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="method">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="accounts">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="account">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="avbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="cfo" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                       &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="depId" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                       &lt;element name="iban" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="cards">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="card">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                                           &lt;element name="mbr" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                           &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                           &lt;element name="expdate" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                                           &lt;element name="ownername" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="avbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                           &lt;element name="creditbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                           &lt;element name="blbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                           &lt;element name="indebtedbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                           &lt;element name="minpaybalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                           &lt;element name="product" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="blbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="creditbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="accountSchema" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="owner" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="contractId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="multibalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="stan" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "result",
    "description",
    "errorcode",
    "method"
})
@XmlRootElement(name = "response")
public class Way4ResponseAccounts {

    protected byte result;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String errorcode;
    @XmlElement(required = true)
    protected Way4ResponseAccounts.Method method;

    /**
     * Gets the value of the result property.
     * 
     */
    public byte getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     */
    public void setResult(byte value) {
        this.result = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the errorcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorcode() {
        return errorcode;
    }

    /**
     * Sets the value of the errorcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorcode(String value) {
        this.errorcode = value;
    }

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link Way4ResponseAccounts.Method }
     *     
     */
    public Way4ResponseAccounts.Method getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link Way4ResponseAccounts.Method }
     *     
     */
    public void setMethod(Way4ResponseAccounts.Method value) {
        this.method = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="accounts">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="account">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="avbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                             &lt;element name="cfo" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                             &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="depId" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                             &lt;element name="iban" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="cards">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="card">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                                                 &lt;element name="mbr" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                                 &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                                 &lt;element name="expdate" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                                                 &lt;element name="ownername" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="avbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                                 &lt;element name="creditbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                                 &lt;element name="blbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                                 &lt;element name="indebtedbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                                 &lt;element name="minpaybalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                                 &lt;element name="product" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="blbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                             &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                             &lt;element name="creditbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                             &lt;element name="accountSchema" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="owner" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="contractId" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="multibalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="stan" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "accounts"
    })
    public static class Method {

        @XmlElement(required = true)
        protected Way4ResponseAccounts.Method.Accounts accounts;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "stan")
        protected Byte stan;

        /**
         * Gets the value of the accounts property.
         * 
         * @return
         *     possible object is
         *     {@link Way4ResponseAccounts.Method.Accounts }
         *     
         */
        public Way4ResponseAccounts.Method.Accounts getAccounts() {
            return accounts;
        }

        /**
         * Sets the value of the accounts property.
         * 
         * @param value
         *     allowed object is
         *     {@link Way4ResponseAccounts.Method.Accounts }
         *     
         */
        public void setAccounts(Way4ResponseAccounts.Method.Accounts value) {
            this.accounts = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the stan property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getStan() {
            return stan;
        }

        /**
         * Sets the value of the stan property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setStan(Byte value) {
            this.stan = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="account">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="avbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                   &lt;element name="cfo" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *                   &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="depId" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *                   &lt;element name="iban" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="cards">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="card">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                                       &lt;element name="mbr" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                                       &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                                       &lt;element name="expdate" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *                                       &lt;element name="ownername" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="avbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                                       &lt;element name="creditbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                                       &lt;element name="blbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                                       &lt;element name="indebtedbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                                       &lt;element name="minpaybalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                                       &lt;element name="product" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="blbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                   &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                   &lt;element name="creditbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                   &lt;element name="accountSchema" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="owner" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="contractId" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="multibalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "account"
        })
        public static class Accounts {

            @XmlElement(required = true)
            protected Way4ResponseAccounts.Method.Accounts.Account account;

            /**
             * Gets the value of the account property.
             * 
             * @return
             *     possible object is
             *     {@link Way4ResponseAccounts.Method.Accounts.Account }
             *     
             */
            public Way4ResponseAccounts.Method.Accounts.Account getAccount() {
                return account;
            }

            /**
             * Sets the value of the account property.
             * 
             * @param value
             *     allowed object is
             *     {@link Way4ResponseAccounts.Method.Accounts.Account }
             *     
             */
            public void setAccount(Way4ResponseAccounts.Method.Accounts.Account value) {
                this.account = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="avbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *         &lt;element name="cfo" type="{http://www.w3.org/2001/XMLSchema}short"/>
             *         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="depId" type="{http://www.w3.org/2001/XMLSchema}short"/>
             *         &lt;element name="iban" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="cards">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="card">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *                             &lt;element name="mbr" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                             &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                             &lt;element name="expdate" type="{http://www.w3.org/2001/XMLSchema}short"/>
             *                             &lt;element name="ownername" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="avbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                             &lt;element name="creditbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                             &lt;element name="blbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                             &lt;element name="indebtedbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                             &lt;element name="minpaybalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                             &lt;element name="product" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="blbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *         &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *         &lt;element name="creditbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *         &lt;element name="accountSchema" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="owner" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="contractId" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="multibalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "avbalance",
                "cfo",
                "currency",
                "depId",
                "iban",
                "id",
                "status",
                "type",
                "cards",
                "blbalance",
                "balance",
                "creditbalance",
                "accountSchema",
                "owner",
                "contractId",
                "multibalance"
            })
            public static class Account {

                protected float avbalance;
                protected short cfo;
                @XmlElement(required = true)
                protected String currency;
                protected short depId;
                protected long iban;
                protected long id;
                protected byte status;
                @XmlElement(required = true)
                protected String type;
                @XmlElement(required = true)
                protected Way4ResponseAccounts.Method.Accounts.Account.Cards cards;
                protected float blbalance;
                protected float balance;
                protected float creditbalance;
                @XmlElement(required = true)
                protected String accountSchema;
                @XmlElement(required = true)
                protected String owner;
                protected long contractId;
                @XmlElement(required = true)
                protected String multibalance;

                /**
                 * Gets the value of the avbalance property.
                 * 
                 */
                public float getAvbalance() {
                    return avbalance;
                }

                /**
                 * Sets the value of the avbalance property.
                 * 
                 */
                public void setAvbalance(float value) {
                    this.avbalance = value;
                }

                /**
                 * Gets the value of the cfo property.
                 * 
                 */
                public short getCfo() {
                    return cfo;
                }

                /**
                 * Sets the value of the cfo property.
                 * 
                 */
                public void setCfo(short value) {
                    this.cfo = value;
                }

                /**
                 * Gets the value of the currency property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCurrency() {
                    return currency;
                }

                /**
                 * Sets the value of the currency property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCurrency(String value) {
                    this.currency = value;
                }

                /**
                 * Gets the value of the depId property.
                 * 
                 */
                public short getDepId() {
                    return depId;
                }

                /**
                 * Sets the value of the depId property.
                 * 
                 */
                public void setDepId(short value) {
                    this.depId = value;
                }

                /**
                 * Gets the value of the iban property.
                 * 
                 */
                public long getIban() {
                    return iban;
                }

                /**
                 * Sets the value of the iban property.
                 * 
                 */
                public void setIban(long value) {
                    this.iban = value;
                }

                /**
                 * Gets the value of the id property.
                 * 
                 */
                public long getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 */
                public void setId(long value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the status property.
                 * 
                 */
                public byte getStatus() {
                    return status;
                }

                /**
                 * Sets the value of the status property.
                 * 
                 */
                public void setStatus(byte value) {
                    this.status = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

                /**
                 * Gets the value of the cards property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Way4ResponseAccounts.Method.Accounts.Account.Cards }
                 *     
                 */
                public Way4ResponseAccounts.Method.Accounts.Account.Cards getCards() {
                    return cards;
                }

                /**
                 * Sets the value of the cards property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Way4ResponseAccounts.Method.Accounts.Account.Cards }
                 *     
                 */
                public void setCards(Way4ResponseAccounts.Method.Accounts.Account.Cards value) {
                    this.cards = value;
                }

                /**
                 * Gets the value of the blbalance property.
                 * 
                 */
                public float getBlbalance() {
                    return blbalance;
                }

                /**
                 * Sets the value of the blbalance property.
                 * 
                 */
                public void setBlbalance(float value) {
                    this.blbalance = value;
                }

                /**
                 * Gets the value of the balance property.
                 * 
                 */
                public float getBalance() {
                    return balance;
                }

                /**
                 * Sets the value of the balance property.
                 * 
                 */
                public void setBalance(float value) {
                    this.balance = value;
                }

                /**
                 * Gets the value of the creditbalance property.
                 * 
                 */
                public float getCreditbalance() {
                    return creditbalance;
                }

                /**
                 * Sets the value of the creditbalance property.
                 * 
                 */
                public void setCreditbalance(float value) {
                    this.creditbalance = value;
                }

                /**
                 * Gets the value of the accountSchema property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAccountSchema() {
                    return accountSchema;
                }

                /**
                 * Sets the value of the accountSchema property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAccountSchema(String value) {
                    this.accountSchema = value;
                }

                /**
                 * Gets the value of the owner property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOwner() {
                    return owner;
                }

                /**
                 * Sets the value of the owner property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOwner(String value) {
                    this.owner = value;
                }

                /**
                 * Gets the value of the contractId property.
                 * 
                 */
                public long getContractId() {
                    return contractId;
                }

                /**
                 * Sets the value of the contractId property.
                 * 
                 */
                public void setContractId(long value) {
                    this.contractId = value;
                }

                /**
                 * Gets the value of the multibalance property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMultibalance() {
                    return multibalance;
                }

                /**
                 * Sets the value of the multibalance property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMultibalance(String value) {
                    this.multibalance = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="card">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}long"/>
                 *                   &lt;element name="mbr" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *                   &lt;element name="expdate" type="{http://www.w3.org/2001/XMLSchema}short"/>
                 *                   &lt;element name="ownername" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="avbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *                   &lt;element name="creditbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *                   &lt;element name="blbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *                   &lt;element name="indebtedbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *                   &lt;element name="minpaybalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *                   &lt;element name="product" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "card"
                })
                public static class Cards {

                    @XmlElement(required = true)
                    protected Way4ResponseAccounts.Method.Accounts.Account.Cards.Card card;

                    /**
                     * Gets the value of the card property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Way4ResponseAccounts.Method.Accounts.Account.Cards.Card }
                     *     
                     */
                    public Way4ResponseAccounts.Method.Accounts.Account.Cards.Card getCard() {
                        return card;
                    }

                    /**
                     * Sets the value of the card property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Way4ResponseAccounts.Method.Accounts.Account.Cards.Card }
                     *     
                     */
                    public void setCard(Way4ResponseAccounts.Method.Accounts.Account.Cards.Card value) {
                        this.card = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}long"/>
                     *         &lt;element name="mbr" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                     *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                     *         &lt;element name="expdate" type="{http://www.w3.org/2001/XMLSchema}short"/>
                     *         &lt;element name="ownername" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="avbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
                     *         &lt;element name="creditbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
                     *         &lt;element name="blbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
                     *         &lt;element name="indebtedbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
                     *         &lt;element name="minpaybalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
                     *         &lt;element name="product" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "number",
                        "mbr",
                        "status",
                        "expdate",
                        "ownername",
                        "currency",
                        "avbalance",
                        "creditbalance",
                        "blbalance",
                        "indebtedbalance",
                        "minpaybalance",
                        "product"
                    })
                    public static class Card {

                        protected long number;
                        protected byte mbr;
                        protected byte status;
                        protected short expdate;
                        @XmlElement(required = true)
                        protected String ownername;
                        @XmlElement(required = true)
                        protected String currency;
                        protected float avbalance;
                        protected float creditbalance;
                        protected float blbalance;
                        protected float indebtedbalance;
                        protected float minpaybalance;
                        @XmlElement(required = true)
                        protected String product;

                        /**
                         * Gets the value of the number property.
                         * 
                         */
                        public long getNumber() {
                            return number;
                        }

                        /**
                         * Sets the value of the number property.
                         * 
                         */
                        public void setNumber(long value) {
                            this.number = value;
                        }

                        /**
                         * Gets the value of the mbr property.
                         * 
                         */
                        public byte getMbr() {
                            return mbr;
                        }

                        /**
                         * Sets the value of the mbr property.
                         * 
                         */
                        public void setMbr(byte value) {
                            this.mbr = value;
                        }

                        /**
                         * Gets the value of the status property.
                         * 
                         */
                        public byte getStatus() {
                            return status;
                        }

                        /**
                         * Sets the value of the status property.
                         * 
                         */
                        public void setStatus(byte value) {
                            this.status = value;
                        }

                        /**
                         * Gets the value of the expdate property.
                         * 
                         */
                        public short getExpdate() {
                            return expdate;
                        }

                        /**
                         * Sets the value of the expdate property.
                         * 
                         */
                        public void setExpdate(short value) {
                            this.expdate = value;
                        }

                        /**
                         * Gets the value of the ownername property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getOwnername() {
                            return ownername;
                        }

                        /**
                         * Sets the value of the ownername property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setOwnername(String value) {
                            this.ownername = value;
                        }

                        /**
                         * Gets the value of the currency property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getCurrency() {
                            return currency;
                        }

                        /**
                         * Sets the value of the currency property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setCurrency(String value) {
                            this.currency = value;
                        }

                        /**
                         * Gets the value of the avbalance property.
                         * 
                         */
                        public float getAvbalance() {
                            return avbalance;
                        }

                        /**
                         * Sets the value of the avbalance property.
                         * 
                         */
                        public void setAvbalance(float value) {
                            this.avbalance = value;
                        }

                        /**
                         * Gets the value of the creditbalance property.
                         * 
                         */
                        public float getCreditbalance() {
                            return creditbalance;
                        }

                        /**
                         * Sets the value of the creditbalance property.
                         * 
                         */
                        public void setCreditbalance(float value) {
                            this.creditbalance = value;
                        }

                        /**
                         * Gets the value of the blbalance property.
                         * 
                         */
                        public float getBlbalance() {
                            return blbalance;
                        }

                        /**
                         * Sets the value of the blbalance property.
                         * 
                         */
                        public void setBlbalance(float value) {
                            this.blbalance = value;
                        }

                        /**
                         * Gets the value of the indebtedbalance property.
                         * 
                         */
                        public float getIndebtedbalance() {
                            return indebtedbalance;
                        }

                        /**
                         * Sets the value of the indebtedbalance property.
                         * 
                         */
                        public void setIndebtedbalance(float value) {
                            this.indebtedbalance = value;
                        }

                        /**
                         * Gets the value of the minpaybalance property.
                         * 
                         */
                        public float getMinpaybalance() {
                            return minpaybalance;
                        }

                        /**
                         * Sets the value of the minpaybalance property.
                         * 
                         */
                        public void setMinpaybalance(float value) {
                            this.minpaybalance = value;
                        }

                        /**
                         * Gets the value of the product property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getProduct() {
                            return product;
                        }

                        /**
                         * Sets the value of the product property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setProduct(String value) {
                            this.product = value;
                        }

                    }

                }

            }

        }

    }

}
